/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import { GlobalComponents } from 'vue'

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Avatar: typeof import('primevue/avatar')['default']
    Badge: typeof import('primevue/badge')['default']
    Button: typeof import('./src/components/ui/button/Button.vue')['default']
    CreateTeacher: typeof import('./src/components/teachers/CreateTeacher.vue')['default']
    CustomButton: typeof import('./src/components/CustomButton.vue')['default']
    FormControl: typeof import('./src/components/ui/form/FormControl.vue')['default']
    FormDescription: typeof import('./src/components/ui/form/FormDescription.vue')['default']
    FormItem: typeof import('./src/components/ui/form/FormItem.vue')['default']
    FormLabel: typeof import('./src/components/ui/form/FormLabel.vue')['default']
    FormMessage: typeof import('./src/components/ui/form/FormMessage.vue')['default']
    Label: typeof import('./src/components/ui/label/Label.vue')['default']
    Loader: typeof import('./src/components/Loader.vue')['default']
    LoginForm: typeof import('./src/components/LoginForm.vue')['default']
    MegaMenu: typeof import('primevue/megamenu')['default']
    Menubar: typeof import('primevue/menubar')['default']
    Modal: typeof import('./src/components/Modal.vue')['default']
    Navbar: typeof import('./src/components/Navbar.vue')['default']
    Pagination: typeof import('./src/components/Pagination.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Searchbar: typeof import('./src/components/Searchbar.vue')['default']
    StudentsTable: typeof import('./src/components/students/StudentsTable.vue')['default']
    TeachersTable: typeof import('./src/components/teachers/TeachersTable.vue')['default']
    Title: typeof import('./src/components/Title.vue')['default']
    TitleBar: typeof import('./src/components/TitleBar.vue')['default']
  }
  export interface GlobalDirectives {
    Ripple: typeof import('primevue/ripple')['default']
  }
}

// For TSX support
declare global {
  const Avatar: typeof import('primevue/avatar')['default']
  const Badge: typeof import('primevue/badge')['default']
  const Button: typeof import('./src/components/ui/button/Button.vue')['default']
  const CreateTeacher: typeof import('./src/components/teachers/CreateTeacher.vue')['default']
  const CustomButton: typeof import('./src/components/CustomButton.vue')['default']
  const FormControl: typeof import('./src/components/ui/form/FormControl.vue')['default']
  const FormDescription: typeof import('./src/components/ui/form/FormDescription.vue')['default']
  const FormItem: typeof import('./src/components/ui/form/FormItem.vue')['default']
  const FormLabel: typeof import('./src/components/ui/form/FormLabel.vue')['default']
  const FormMessage: typeof import('./src/components/ui/form/FormMessage.vue')['default']
  const Label: typeof import('./src/components/ui/label/Label.vue')['default']
  const Loader: typeof import('./src/components/Loader.vue')['default']
  const LoginForm: typeof import('./src/components/LoginForm.vue')['default']
  const MegaMenu: typeof import('primevue/megamenu')['default']
  const Menubar: typeof import('primevue/menubar')['default']
  const Modal: typeof import('./src/components/Modal.vue')['default']
  const Navbar: typeof import('./src/components/Navbar.vue')['default']
  const Pagination: typeof import('./src/components/Pagination.vue')['default']
  const RouterLink: typeof import('vue-router')['RouterLink']
  const RouterView: typeof import('vue-router')['RouterView']
  const Searchbar: typeof import('./src/components/Searchbar.vue')['default']
  const StudentsTable: typeof import('./src/components/students/StudentsTable.vue')['default']
  const TeachersTable: typeof import('./src/components/teachers/TeachersTable.vue')['default']
  const Title: typeof import('./src/components/Title.vue')['default']
  const TitleBar: typeof import('./src/components/TitleBar.vue')['default']
}