/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import { GlobalComponents } from 'vue'

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Avatar: typeof import('primevue/avatar')['default']
    Badge: typeof import('primevue/badge')['default']
    Button: typeof import('primevue/button')['default']
    Loader: typeof import('./src/components/Loader.vue')['default']
    MegaMenu: typeof import('primevue/megamenu')['default']
    Menubar: typeof import('primevue/menubar')['default']
    Navbar: typeof import('./src/components/Navbar.vue')['default']
    Pagination: typeof import('./src/components/Pagination.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Searchbar: typeof import('./src/components/Searchbar.vue')['default']
    TeachersTable: typeof import('./src/components/teachers/TeachersTable.vue')['default']
    Title: typeof import('./src/components/Title.vue')['default']
  }
  export interface GlobalDirectives {
    Ripple: typeof import('primevue/ripple')['default']
  }
}

// For TSX support
declare global {
  const Avatar: typeof import('primevue/avatar')['default']
  const Badge: typeof import('primevue/badge')['default']
  const Button: typeof import('primevue/button')['default']
  const Loader: typeof import('./src/components/Loader.vue')['default']
  const MegaMenu: typeof import('primevue/megamenu')['default']
  const Menubar: typeof import('primevue/menubar')['default']
  const Navbar: typeof import('./src/components/Navbar.vue')['default']
  const Pagination: typeof import('./src/components/Pagination.vue')['default']
  const RouterLink: typeof import('vue-router')['RouterLink']
  const RouterView: typeof import('vue-router')['RouterView']
  const Searchbar: typeof import('./src/components/Searchbar.vue')['default']
  const TeachersTable: typeof import('./src/components/teachers/TeachersTable.vue')['default']
  const Title: typeof import('./src/components/Title.vue')['default']
}